apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-nodes
  namespace: db
  labels:
    app: postgres-nodes
    app.kubernetes.io/name: postgres-cluster
    app.kubernetes.io/component: database
    role: data
spec:
  serviceName: postgres-nodes
  replicas: 4  # 1 primary + 1 sync + 2 async replicas
  podManagementPolicy: OrderedReady  # MUST be sequential for pg_auto_failover
  selector:
    matchLabels:
      app: postgres-nodes
  template:
    metadata:
      labels:
        app: postgres-nodes
        app.kubernetes.io/name: postgres-cluster
        app.kubernetes.io/component: database
        role: data
    spec:
      securityContext:
        fsGroup: 101
        runAsUser: 101
        runAsGroup: 101
      terminationGracePeriodSeconds: 60
      # Anti-affinity: spread postgres pods across different nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: postgres-nodes
                topologyKey: kubernetes.io/hostname
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: postgres-nodes
                topologyKey: topology.kubernetes.io/zone
      # Topology spread: ensure even distribution
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: postgres-nodes
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: postgres-nodes
      initContainers:
      - name: initdb
        image: citusdata/pg_auto_failover:latest  # Use 'latest' for now, pin after verifying available tags
        command: ["/bin/bash", "/etc/scripts/init-node.sh"]
        securityContext:
          runAsGroup: 101
          runAsUser: 101
        env:
        - name: PGDATA
          value: /var/lib/postgresql/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql
        - name: postgres-secrets
          mountPath: /etc/secrets
          readOnly: true
        - name: pg-auto-failover-config
          mountPath: /etc/scripts
          readOnly: true
        - name: shared-config
          mountPath: /shared
      containers:
      - name: postgres
        image: citusdata/pg_auto_failover:latest  # Use 'latest' for now, pin after verifying available tags
        env:
        - name: PGDATA
          value: /var/lib/postgresql/pgdata
        - name: PG_AUTOCTL_MONITOR
          value: postgres://autoctl_node@postgres-monitor.db.svc.cluster.local:6001/pg_auto_failover
        command: ["/bin/bash", "/etc/scripts/start-node.sh"]
        securityContext:
          runAsGroup: 101
          runAsUser: 101
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql
        - name: postgres-secrets
          mountPath: /etc/secrets
          readOnly: true
        - name: pg-auto-failover-config
          mountPath: /etc/pg-auto-failover
          readOnly: true
        - name: pg-auto-failover-config
          mountPath: /etc/scripts
          readOnly: true
        - name: shared-config
          mountPath: /shared
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              export PATH="/usr/lib/postgresql/11/bin:/usr/local/bin:$PATH"
              # Check if postgres is ready on standard port 5432
              pg_isready -h localhost -p 5432 -U postgres
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              NODE_NAME=$(hostname)
              case $NODE_NAME in
                *-0) PGDATA="/var/lib/postgresql/pgdata/master" ;;
                *-1) PGDATA="/var/lib/postgresql/pgdata/syncreplica" ;;
                *-2) PGDATA="/var/lib/postgresql/pgdata/asyncreplica" ;;
                *-3) PGDATA="/var/lib/postgresql/pgdata/asyncreplica" ;;
                *) PGDATA="/var/lib/postgresql/pgdata/replica" ;;
              esac
              export PATH="/usr/lib/postgresql/11/bin:/usr/local/bin:$PATH"

              # Check if pg_autoctl process is running (most important)
              if ! pgrep -f "pg_autoctl run" > /dev/null; then
                echo "pg_autoctl process not running"
                exit 1
              fi

              # Check postgres connectivity on standard port 5432
              if ! pg_isready -h localhost -p 5432 -U postgres -t 5; then
                echo "PostgreSQL not ready"
                exit 1
              fi
          initialDelaySeconds: 30
          periodSeconds: 45
          timeoutSeconds: 15
          successThreshold: 1
          failureThreshold: 4
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                NODE_NAME=$(hostname)
                case $NODE_NAME in
                  *-0) PGDATA="/var/lib/postgresql/pgdata/master" ;;
                  *-1) PGDATA="/var/lib/postgresql/pgdata/syncreplica" ;;
                  *-2) PGDATA="/var/lib/postgresql/pgdata/asyncreplica" ;;
                  *-3) PGDATA="/var/lib/postgresql/pgdata/asyncreplica" ;;
                  *) PGDATA="/var/lib/postgresql/pgdata/replica" ;;
                esac
                pg_autoctl stop --pgdata $PGDATA --fast
                sleep 5
      - name: pod-labeler
        securityContext:
          runAsUser: 101
          runAsGroup: 101
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
        # Using pre-built image with dependencies (see images/pod-labeler/Dockerfile)
        # For now, using python slim with pip install
        image: python:3.11-slim-bookworm
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - |
            pip install --user --no-cache-dir psycopg2-binary kubernetes && \
            echo "Pip install succeeded" && \
            python -u /mnt/labeler.py
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: labeler-script
            mountPath: /mnt/labeler.py
            subPath: labeler.py

      volumes:
      - name: labeler-script
        configMap:
          name: pod-labeler-script
      - name: postgres-secrets
        secret:
          secretName: postgres-creds
      - name: pg-auto-failover-config
        configMap:
          name: pg-auto-failover-config
          defaultMode: 0755
      - name: shared-config
        emptyDir: {}
      restartPolicy: Always
      serviceAccountName: postgres-service-account
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi
      storageClassName: standard