apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-replicas
  namespace: db
  labels:
    app: pgbouncer-replicas
    app.kubernetes.io/name: postgres-cluster
    app.kubernetes.io/component: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer-replicas
  template:
    metadata:
      labels:
        app: pgbouncer-replicas
        app.kubernetes.io/name: postgres-cluster
        app.kubernetes.io/component: pgbouncer
    spec:
      # Anti-affinity to spread pgbouncer pods
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/component: pgbouncer
                topologyKey: kubernetes.io/hostname
      initContainers:
      - name: config-init
        image: busybox:1.36  # Pinned version
        command:
        - /bin/sh
        - -c
        - |
          # Copy config files to writable location
          cp /etc/pgbouncer-ro/* /etc/pgbouncer/
          chmod 644 /etc/pgbouncer/*
        volumeMounts:
        - name: pgbouncer-config-ro
          mountPath: /etc/pgbouncer-ro
          readOnly: true
        - name: pgbouncer-config-rw
          mountPath: /etc/pgbouncer
      containers:
      - name: pgbouncer
        image: edoburu/pgbouncer:latest  # Use 'latest' for now
        ports:
        - containerPort: 6432
          name: pgbouncer
        env:
        - name: DATABASES_HOST
          value: "postgres-replicas.db.svc.cluster.local"
        - name: DATABASES_PORT
          value: "5432"
        - name: DATABASES_USER
          value: "postgres"
        - name: DATABASES_DBNAME
          value: "postgres"
        - name: DATABASES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: postgres-password
        - name: POOL_MODE
          value: "transaction"
        - name: DEFAULT_POOL_SIZE
          value: "10"
        - name: MAX_CLIENT_CONN
          value: "100"
        volumeMounts:
        - name: pgbouncer-config-rw
          mountPath: /etc/pgbouncer
        - name: postgres-secrets
          mountPath: /etc/secrets
          readOnly: true
        command:
        - /bin/sh
        - -c
        - |
          # Update config with runtime values
          sed -i "s/DATABASES_HOST/${DATABASES_HOST}/g" /etc/pgbouncer/pgbouncer.ini
          sed -i "s/DATABASES_PORT/${DATABASES_PORT}/g" /etc/pgbouncer/pgbouncer.ini
          sed -i "s/DATABASES_USER/${DATABASES_USER}/g" /etc/pgbouncer/pgbouncer.ini
          sed -i "s/DATABASES_DBNAME/${DATABASES_DBNAME}/g" /etc/pgbouncer/pgbouncer.ini
          sed -i "s/DATABASES_PASSWORD/${DATABASES_PASSWORD}/g" /etc/pgbouncer/pgbouncer.ini

          # Start PgBouncer (edoburu image uses direct pgbouncer command)
          exec pgbouncer /etc/pgbouncer/pgbouncer.ini
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: 6432
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6432
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
      - name: pgbouncer-config-ro
        configMap:
          name: pgbouncer-config
      - name: pgbouncer-config-rw
        emptyDir: {}
      - name: postgres-secrets
        secret:
          secretName: postgres-creds
