apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-monitor
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-monitor
  template:
    metadata:
      labels:
        app: postgres-monitor
    spec:
      securityContext:
        fsGroup: 101
        runAsUser: 101
        runAsGroup: 101
      containers:
        - name: postgres-monitor
          image: citusdata/pg_auto_failover:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              #!/bin/bash
              set -eux
              
              # Set PATH to include PostgreSQL binaries
              export PATH="/usr/lib/postgresql/11/bin:/usr/local/bin:$PATH"
              
              # Create data directory with proper permissions
              mkdir -p /var/lib/postgresql/pgdata
              
              # Set PostgreSQL environment variables
              export PGDATA=/var/lib/postgresql/pgdata/monitor
              export PGPORT=6001
              export PGUSER=postgres
              
              # Get container IP
              MY_IP=$(hostname -i)
              
              # Initialize the monitor
              pg_autoctl create monitor \
                --hostname "$MY_IP" \
                --pgport "$PGPORT" \
                --auth trust \
                --ssl-self-signed \
                --pgdata "$PGDATA" \
                --run

          securityContext:
            runAsUser: 101
            runAsGroup: 101
          ports:
            - containerPort: 6001
              name: postgres
          env:
            - name: PGDATA
              value: /var/lib/postgresql/pgdata/monitor
            - name: PGPORT
              value: "6001"
            - name: PGUSER
              value: postgres
            - name: PATH
              value: "/usr/lib/postgresql/11/bin:/usr/local/bin:/usr/bin:/bin"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/pgdata
          # Add readiness and liveness probes
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  export PATH="/usr/lib/postgresql/11/bin:/usr/local/bin:$PATH"
                  pg_isready -h localhost -p 6001 -U postgres
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  export PATH="/usr/lib/postgresql/11/bin:/usr/local/bin:$PATH"
                  pg_isready -h localhost -p 6001 -U postgres
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-monitor-pvc