apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: db
spec:
  containers:
    - name: debug
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: debug-vol
          mountPath: /mnt
  volumes:
    - name: debug-vol
      persistentVolumeClaim:
        claimName: postgres-monitor-pvc
  restartPolicy: Never

