networks:
  postgres-cluster:
    driver: bridge

volumes:
  postgres-master-data:
  postgres-async-replica-data:
  postgres-sync-replica-data:

services:
  postgres-master:
    image: postgres:16
    container_name: postgres-master
    hostname: postgres-master
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_REPLICATION_USER: replicauser
      POSTGRES_REPLICATION_PASSWORD: replicauser123
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    volumes:
      - postgres-master-data:/var/lib/postgresql/data
      - ./master-configuration/init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
      - ./master-configuration/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./master-configuration/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    networks:
      - postgres-cluster
    healthcheck:
      test: ["CMD", "true"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-sync-replica:
    image: postgres:16
    container_name: postgres-sync-replica
    hostname: postgres-sync-replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      PGUSER: postgres
      POSTGRES_MASTER_SERVICE: postgres-master
      POSTGRES_REPLICATION_USER: replicauser
      POSTGRES_REPLICATION_PASSWORD: replicauser123
      POSTGRES_HOST_AUTH_METHOD: trust
      REPLICA_TYPE: sync
    volumes:
      - postgres-sync-replica-data:/var/lib/postgresql/data
      - ./replica-configuration/init-replica-mixed.sh:/tmp/init-replica.sh:ro
      - ./replica-configuration/postgresql-sync.conf:/etc/postgresql/postgresql.conf:ro
      - ./replica-configuration/unified-replica.sh:/tmp/entrypoint.sh:ro
    ports:
      - "5433:5432"
    networks:
      - postgres-cluster
    depends_on:
      postgres-master:
        condition: service_healthy
    entrypoint: ["bash", "/tmp/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "true"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  postgres-async-replica:
    image: postgres:16
    container_name: postgres-async-replica
    hostname: postgres-async-replica
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      PGUSER: postgres
      POSTGRES_MASTER_SERVICE: postgres-master
      POSTGRES_REPLICATION_USER: replicauser
      POSTGRES_REPLICATION_PASSWORD: replicauser123
      POSTGRES_HOST_AUTH_METHOD: trust
      REPLICA_TYPE: async
    volumes:
      - postgres-async-replica-data:/var/lib/postgresql/data
      - ./replica-configuration/init-replica-mixed.sh:/tmp/init-replica.sh:ro
      - ./replica-configuration/async-replica-postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./replica-configuration/unified-replica.sh:/tmp/entrypoint.sh:ro
    ports:
      - "5434:5432"
    networks:
      - postgres-cluster
    depends_on:
      postgres-master:
        condition: service_healthy
    entrypoint: ["bash", "/tmp/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "true"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s