apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-monitor-pvc
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard  # Use default storage class
