apiVersion: v1
kind: Service
metadata:
  name: postgres-monitor
  namespace: db
  labels:
    app: postgres-monitor
    app.kubernetes.io/name: postgres-cluster
    app.kubernetes.io/component: monitor
spec:
  selector:
    app: postgres-monitor
  ports:
    - name: monitor
      port: 6001
      targetPort: 6001
      protocol: TCP
  type: ClusterIP