# Service to expose the PostgreSQL nodes
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodes
  namespace: db
  labels:
    app: postgres-nodes
spec:
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - name: postgres-0
    port: 6002
    targetPort: 6002
  - name: postgres-1
    port: 6003
    targetPort: 6003
  - name: postgres-2
    port: 6004
    targetPort: 6004
  - name: postgres-3
    port: 6005
    targetPort: 6005
  selector:
    app: postgres-nodes