apiVersion: v1
kind: Service
metadata:
  name: postgres-nodes
  namespace: db
  labels:
    app: postgres-nodes
spec:
  selector:
    app: postgres-nodes
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  clusterIP: None
  type: ClusterIP