# Service for read replicas
apiVersion: v1
kind: Service
metadata:
  name: postgres-replicas
  namespace: db
spec:
  selector:
    app: postgres-nodes
  ports:
  - name: postgres-1
    port: 6003
    targetPort: 6003
  - name: postgres-2
    port: 6004
    targetPort: 6004
  - name: postgres-3
    port: 6005
    targetPort: 6005
  type: ClusterIP