# Service to expose the PostgreSQL nodes
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodes
  namespace: db
  labels:
    app: postgres-nodes
spec:
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: postgres-nodes