apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: db
  labels:
    app: db
spec:
  selector:
    app: postgres-nodes
    role: primary  # This will be managed by pg_auto_failover
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP