# Service for accessing the current primary
apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
  namespace: db
spec:
  selector:
    app: postgres-nodes
  ports:
  - name: postgres
    port: 5432
    targetPort: 6002  # Will need dynamic update based on current primary
  type: ClusterIP