# ConfigMap for pg_auto_failover specific settings
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-auto-failover-config
  namespace: db
data:
  init-node.sh: |
    #!/bin/bash
    set -e

    NODE_NAME=$(hostname)
    export MONITOR_URI="postgres://autoctl_node@postgres-monitor.db.svc.cluster.local:6001/pg_auto_failover"

    case $NODE_NAME in
      *-0)
        PRIORITY=100
        mkdir -p /var/lib/postgresql/pgdata
        export PGDATA=/var/lib/postgresql/pgdata/master
        export PGPORT=6002
        export PGUSER=postgres
        ;;
      *-1)
        PRIORITY=90
        mkdir -p /var/lib/postgresql/pgdata
        export PGDATA=/var/lib/postgresql/pgdata/syncreplica
        export PGPORT=6003
        export PGUSER=postgres
        ;;
      *-2)
        PRIORITY=80
        mkdir -p /var/lib/postgresql/pgdata
        export PGDATA=/var/lib/postgresql/pgdata/asyncreplica
        export PGPORT=6004
        export PGUSER=postgres
        ;;
      *-3)
        PRIORITY=70
        mkdir -p /var/lib/postgresql/pgdata
        export PGDATA=/var/lib/postgresql/pgdata/asyncreplica2
        export PGPORT=6005
        export PGUSER=postgres
        ;;
      *)
        PRIORITY=60
        mkdir -p /var/lib/postgresql/pgdata
        export PGDATA=/var/lib/postgresql/pgdata/replica
        export PGPORT=6006
        export PGUSER=postgres
        ;;
    esac

    MY_IP=$(hostname -i)

    pg_autoctl create postgres \
      --hostname "${NODE_NAME}.postgres-nodes.db.svc.cluster.local" \
      --monitor "$MONITOR_URI" \
      --pgport "$PGPORT" \
      --auth trust \
      --ssl-self-signed \
      --pgdata "$PGDATA"

    echo "Pg_autoctl initialization for master node completed"
    echo "Setup completed"

  start-node.sh: |
      #!/bin/bash
      set -e

      NODE_NAME=$(hostname)
      export MONITOR_URI="postgres://autoctl_node@postgres-monitor.db.svc.cluster.local:6001/pg_auto_failover"
      case $NODE_NAME in
        *-0)
          PRIORITY=100
          mkdir -p /var/lib/postgresql/pgdata
          export PGDATA=/var/lib/postgresql/pgdata/master
          export PGPORT=6002
          export PGUSER=postgres
          ;;
        *-1)
          PRIORITY=90
          mkdir -p /var/lib/postgresql/pgdata
          export PGDATA=/var/lib/postgresql/pgdata/syncreplica
          export PGPORT=6003
          export PGUSER=postgres
          ;;
        *-2)
          PRIORITY=80
          mkdir -p /var/lib/postgresql/pgdata
          export PGDATA=/var/lib/postgresql/pgdata/asyncreplica
          export PGPORT=6004
          export PGUSER=postgres
          ;;
        *-3)
          PRIORITY=70
          mkdir -p /var/lib/postgresql/pgdata
          export PGDATA=/var/lib/postgresql/pgdata/asyncreplica2
          export PGPORT=6005
          export PGUSER=postgres
          ;;
        *)
          PRIORITY=60
          mkdir -p /var/lib/postgresql/pgdata
          export PGDATA=/var/lib/postgresql/pgdata/replica
          export PGPORT=6006
          export PGUSER=postgres
          ;;
        esac
        pg_autoctl run --pgdata "$PGDATA"