apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbouncer-config
  namespace: db
data:
  pgbouncer.ini: |
    [databases]
    postgres = host=DATABASES_HOST port=DATABASES_PORT dbname=DATABASES_DBNAME user=DATABASES_USER password=DATABASES_PASSWORD sslmode=require

    [pgbouncer]
    listen_port = 6432
    listen_addr = *
    auth_type = trust  # Use trust for testing, md5 for production
    admin_users = postgres
    stats_users = postgres
    pool_mode = transaction
    default_pool_size = 10
    max_client_conn = 100
    reserve_pool_size = 2
    reserve_pool_timeout = 5
    max_db_connections = 50
    max_user_connections = 50
    server_reset_query = DISCARD ALL
    server_check_query = select 1
    server_check_delay = 30
    log_connections = 1
    log_disconnections = 1
    log_pooler_errors = 1
    verbose = 1
    ignore_startup_parameters = extra_float_digits
    server_tls_sslmode = require

  userlist.txt: |
    # For trust authentication, this can be empty
    # For md5 authentication, add: "postgres" "md5hash"