apiVersion: v1
kind: Secret
metadata:
    name: postgres-creds
    namespace: db
type: Opague
data:
  # Default: postgres / postgres123
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXMxMjM=

  # Default: replicator / replicauser123
  replicator-user: cmVwbGljYXRvcg==
  replicator-password: cmVwbGljYXVzZXIxMjM=

  # Default: autoctl_node / autoctl_node123
  monitor-user: YXV0b2N0bF9ub2Rl
  monitor-password: YXV0b2N0bF9ub2RlMTIz

  # Default: appuser
  app-user: YXBwdXNlcg==
  app-password: YXBwdXNlcjEyMw==